[workspace]
members = ["contracts/*", "amm/contracts/*"]

# Resolver has to be set explicitely in workspaces, see https://github.com/rust-lang/cargo/issues/9956
resolver = "2"

[profile.release]
overflow-checks = false
